runtime_dir_path: "./runtime"
borzoi_config_path: "./borzoi.yaml"
server_host: "0.0.0.0"
server_port: "8080"

redis_host: "127.0.0.1"
redis_port: "6379"
redis_password: "weakpassword2"
redis_db: 0

request_timeout: 60s
enable_watcher: false
max_port_search_iterations: 100

default_port_range_min: 40000
default_port_range_max: 49152

nginx_sites_available_path: "/etc/nginx/sites-available"
nginx_sites_enabled_path: "/etc/nginx/sites-enabled"
hosts_file_path: "/etc/hosts"
